Fix typing for `createManager`
react-boilerplate/redux-injectors pull request #36
Opened 2022-07-05 16:01 UTC by mrfratello

2022-07-06 04:07 UTC, BenLorantfy requested changes
Hey @mrfratello , thanks for the fix 🙂 

Had one request before merging.

2022-07-06 04:07 UTC, BenLorantfy commented on index.d.ts
>   */
Do you mind also updating the documentation here: https://github.com/react-boilerplate/redux-injectors/blob/master/src/createManager.js#L4-L21

Unfortunately there's duplicate documentation.  

After you update that comment, you can run `npm run build:docs` and it will update the generated markdown docs

2022-07-06 09:33 UTC, mrfratello commented on index.d.ts
>   */
thanks for the review and tips on npm scripts. I also corrected the documentation.

2022-07-17 19:29 UTC, BenLorantfy approved these changes
Looks good, thanks @mrfratello 🙂

2022-07-17 19:30 UTC, merged